platform :ios, '11.0'

plugin 'cocoapods-pod-merge'
install! "cocoapods", :warn_for_unused_master_specs_repo => false

target 'PodMergeExample' do
  use_frameworks!

  pod 'Nuke' # Unmerged pods are unaffected

  # Merged Pods:
  pod 'Networking', :path => 'MergedPods/Networking'
  pod 'UI', :path => 'MergedPods/UI'
  pod 'AlamofireGroup', :path => 'MergedPods/AlamofireGroup'
  pod 'MergedSwiftPods', :path => 'MergedPods/MergedSwiftPods'
  pod 'Subspecs', :path => 'MergedPods/Subspecs'
end
