platform :ios, '11.0'

plugin 'cocoapods-pod-merge'

target 'PodMergeExample' do
  use_frameworks!

  pod 'SnapKit' # Unmerged pods are unaffected

  # Merged Pods:
  pod 'Networking', :path => 'MergedPods/Networking'
  pod 'UI', :path => 'MergedPods/UI'
  pod 'MergedSwiftPods', :path => 'MergedPods/MergedSwiftPods'
end
